# Generated by Django 4.1.13 on 2024-02-19 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='url',
        ),
    ]
