version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - selenium

  selenium:
    build:
      context: ./selenium
      dockerfile: Dockerfile.selenium
